Controllers/AuthTokenController.cs
using Microsoft.AspNetCore.Mvc;
using RetoFactus.Services;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Caching.Memory;

namespace RetoFactus.Controllers
{
    public class AuthTokenController : Controller
    {
        private readonly AuthService _authService;

        public AuthTokenController(AuthService authService)
        {
            _authService = authService;
        }
        [HttpPost]
        public async Task<IActionResult> getToken(string user, string pwd)
        {
            try
            {
                var token = await _authService.GetAccesToken(user, pwd);
                return RedirectToAction("BillsView", "Bills");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error al obtener el token");
                return BadRequest(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> RefreshToken()
        {
            var tokenR = await _authService.RefreshToken();
            return Ok(tokenR);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RetoFactus.Models;

namespace RetoFactus.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult CreateBill()
        {
            return View();
        }
        public IActionResult BillsView()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["OcultarMenu"] = true;
}

<div class="container-sm">
    <div class="row text-center">
        <div class="p-5 col-6">
            <h1>RETO FACTUS</h1>
        </div>
        <div class="p-5 col-6">
            <div class="col-1 align-content-center text-center">
                <form method="post" asp-controller="AuthToken" asp-action="getToken" onsubmit="mostrarCargando()">
                    <label>Correo</label>
                    <input type="email" name="user" value="sandbox@factus.com.co">
                    <label>Contraseña</label>
                    <input type="password" name="pwd" value="sandbox2024%">
                    <input class="m-2" type="submit" value="Iniciar sesión">
                </form>
            </div>
        </div>
    </div>
</div>